version: '3'

services:
  flask_app:
    build: .
    ports:
      - '5002:5000'
    depends_on:
      - db

  db:
    image: postgres:15
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres 
      - POSTGRES_DB=boulder_db